variables:
  MARIADB_DATABASE: "sl-projects_main"
  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  MAIN_DB_HOST: "mariadb"
  MAIN_DB_USERNAME: "root"
  SC_DB_HOST: "mariadb"
  SC_DB_USERNAME: "root"

default:
  image: registry.gitlab.sl-projects.com/sofianelasri/sl-projects-website:latest
  services:
    - mariadb:11

stages:
  - setup
  - test
  - deploy

setup_mariadb:
  stage: setup
  services:
    - mariadb:11
  script:
    - echo "CREATE DATABASE IF NOT EXISTS sl-projects_showcase;" | mariadb -u root -h "${MAIN_DB_HOST}"

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit

deploy_production:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: https://sofianelasri.fr
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
