/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        "login": [],
        "logout": [],
        "password.request": [],
        "password.reset": [
            {
                "name": "token"
            }
        ],
        "password.email": [],
        "password.update": [],
        "register": [],
        "user-profile-information.update": [],
        "user-password.update": [],
        "password.confirmation": [],
        "password.confirm": [],
        "two-factor.login": [],
        "two-factor.enable": [],
        "two-factor.confirm": [],
        "two-factor.disable": [],
        "two-factor.qr-code": [],
        "two-factor.secret-key": [],
        "two-factor.recovery-codes": [],
        "sanctum.csrf-cookie": [],
        "livewire.update": [],
        "livewire.upload-file": [],
        "livewire.preview-file": [
            {
                "name": "filename"
            }
        ],
        "ignition.healthCheck": [],
        "ignition.executeSolution": [],
        "ignition.updateConfig": [],
        "sofianelasri.home": [],
        "sofianelasri.": [],
        "showcase.home": [],
        "showcase.projects": [],
        "showcase.project": [
            {
                "name": "project"
            }
        ],
        "showcase.": [
            {
                "name": "path"
            }
        ],
        "dashboard.home": [],
        "dashboard.media-library.page": [],
        "dashboard.media-library.get-uploaded-files": [],
        "dashboard.ajax.set-sidebar-state": [],
        "dashboard.ajax.projects.check-slug": [],
        "dashboard.ajax.projects.check-name": [],
        "dashboard.ajax.components.media-upload-zone.find-icon": [],
        "dashboard.ajax.components.media-upload-zone.upload-file": [],
        "dashboard.projects.add": [],
        "dashboard.": []
    }
}
export {};
