image: docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:20.10.16-dind
    alias: docker
    command: ["--tls=false"]

